# Generated by Django 4.2.6 on 2024-05-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TemplateData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtemplate',
            name='displayStyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TemplateData.displaystyle'),
        ),
    ]
