# Generated by Django 5.0.6 on 2024-05-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
                ('image', models.CharField(max_length=300, unique=True)),
                ('text', models.CharField(max_length=3000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title_de', models.CharField(max_length=300, unique=True)),
                ('desc_de', models.CharField(max_length=1000, unique=True)),
                ('title_en', models.CharField(max_length=300, unique=True)),
                ('desc_en', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.ManyToManyField(related_name='about_me', to='freundebuch_db.answer')),
                ('country_of_origin', models.ManyToManyField(related_name='country_of_origin', to='freundebuch_db.answer')),
                ('date_of_birth', models.ManyToManyField(related_name='date_of_birth', to='freundebuch_db.answer')),
                ('entry_image', models.ManyToManyField(related_name='entry_image', to='freundebuch_db.answer')),
                ('first_encounter', models.ManyToManyField(related_name='first_encounter', to='freundebuch_db.answer')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.user')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTemplateHasQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.interviewtemplate')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.question')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.answer')),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.interview')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.question'),
        ),
        migrations.AddField(
            model_name='interview',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.user'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('basic_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.basicinfo')),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.interview')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.user')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freundebuch_db.user'),
        ),
    ]
