# Generated by Django 4.2.6 on 2024-05-22 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TemplateData', '0001_initial'),
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TemplateData.question'),
        ),
        migrations.AddField(
            model_name='entry',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TemplateData.entrytemplate'),
        ),
        migrations.AddField(
            model_name='interview',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TemplateData.interviewtemplate'),
        ),
    ]
